[package]
name = "turbo-mock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
bindgen = "0.61.0"
build-target = "0.4.0"

[dependencies]
